server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "same-origin" always;
    add_header Content-Security-Policy "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self' data:; connect-src 'self'; frame-ancestors http://192.168.20.102:3001 http://homepage.home.local:3001 http://100.94.122.18:3001 http://docker-host:3001 http://docker-host.tail7012a0.ts.net:3001" always;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
