services:
  telegraf:
    image: telegraf@sha256:386b2d4fdd4265d9e5b6a20131dbfe2b6bc277a4d53972962e5a4a3d16f180ef
    container_name: docker-host-telegraf
    restart: unless-stopped
    user: telegraf:998
    group_add:
      - "${DOCKER_SOCK_GID:-989}"
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /:/hostfs:ro,rslave
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      HOST_ETC: /hostfs/etc
      HOST_PROC: /hostfs/proc
      HOST_SYS: /hostfs/sys
      HOST_VAR: /hostfs/var
      HOST_RUN: /hostfs/run
      HOST_MOUNT_PREFIX: /hostfs
      INFLUXDB_TOKEN: ${INFLUXDB_TOKEN}

networks:
  default:
    name: docker-host-telegraf
    ipam:
      config:
        - subnet: 10.240.22.0/24
