- Reference Links:
    - Tailscale:
        - icon: tailscale.png
          href: https://login.tailscale.com/admin/machines
    - Project Repository:
        - icon: github.png
          href: https://github.com/Nysplaidame/home-automation-project
    - Homepage Documentation:
        - icon: homepage.png
          href: https://gethomepage.dev/
