# ESPHome PrintAirPipe Controller Configuration - Placeholder
# This will contain the actual PrintAirPipe configuration


#
# Architecture Context: [[docs/decisions/001-network-architecture]]
# Network Assignment: VLAN 50 (IoT Sensors) - 192.168.50.0/24  
# Project Status: [[Main/Home Automation/Readme]]
# Safety Priority: CRITICAL - Fire detection and emergency ventilation control
#
# Related Documents:
# - [[docs/diagrams/Network Diagram - Revised]] - Network topology showing VLAN 50
# - [[configs/openwrt/firewall-config.sh]] - Network security rules
# - [[configs/home-assistant/configuration.yaml]] - HA integration (pending)
#
# SAFETY NOTE: This device operates on isolated VLAN 50 with no internet access
# for maximum security of fire safety systems.
#
# PrintAirPipe Resources:
# - Hardware STL: https://nerdiy.de/en/product-2/printairpipe-125-actuator-sensor-set-3d-printable-stl-files/
# - ESPHome Code: https://github.com/Nerdiyde/ESPHomeSnippets/tree/c0135795dc180c6ff4a1306b2f5982ef3db386c3/Snippets/PrintAirPipe