# Home Assistant Automations - Placeholder
# Fire safety and automation rules will be added here


#
# Architecture Context: [[docs/decisions/001-network-architecture]]
# Network Assignment: VLAN 20 (Automation) - 192.168.20.101
# Project Status: [[Main/Home Automation/Readme]]
# Safety Focus: Fire detection and emergency response automation
#
# Related Documents:  
# - [[configs/home-assistant/configuration.yaml]] - Main HA configuration
# - [[configs/esphome/printairpipe-controller.yaml]] - Fire safety sensor integration
# - [[configs/openwrt/firewall-config.sh]] - Network security enabling sensor access
# - [[docs/diagrams/Network Diagram - Revised]] - Complete system topology
#
# Critical Safety Automations (Planned):
# - Fire Detection Response: Smoke sensors → Emergency smart plug cutoff
# - Air Quality Management: VOC sensors → PrintAirPipe ventilation control  
# - Temperature Monitoring: Overheating → Automatic printer shutdown
# - Emergency Protocols: Manual override → Direct smart plug control
#
# Sensor Integrations:
# - VLAN 50 Sensors: Temperature, humidity, smoke, VOC, pressure
# - Smart Plugs: SLA printer (50.71), FDM printer (50.72)
# - Servo Controller: PrintAirPipe ventilation system (50.80)