name: atsumeru

services:
  atsumeru:
    image: atsumerudev/atsumeru@sha256:16ee7196726ac343c57353435dca8f5ce240a02e50babf97e1a1c24da74c3aef
    container_name: atsumeru
    user: "${MEDIA_UID}:${MEDIA_GID}"
    restart: unless-stopped
    ports:
      - "31337:31337"
    volumes:
      - /mnt/omv/media/comics/atsumeru-library:/library
      - ./config:/app/config
      - ./database:/app/database
      - ./cache:/app/cache
      - ./logs:/app/logs
    security_opt:
      - no-new-privileges:true

networks:
  default:
    name: atsumeru
    ipam:
      config:
        - subnet: 10.240.12.0/24
